const LOGIN = "LOGIN"
const LOGOUT = "LOGOUT"
const AUDIO_FILE = "AUDIO_FILE"
const AUDIO_PLAY = "AUDIO_PLAY"
const AUDIO_PAUSE = "AUDIO_PAUSE"
const AUDIO_VOLUME = "AUDIO_VOLUME"
const AUDIO_TIME = "AUDIO_TIME"
const DURATION = "DURATION"
const HEADER = "HEADER"
const CLEAR_AUDIO = "CLEAR_AUDIO"
const OPEN_SIDE_PAGE = "OPEN_SIDE_PAGE"
const CLOSE_SIDE_PAGE = "CLOSE_SIDE_PAGE"
const SIDE_PAGE = "SIDE_PAGE"
const AUDIO_LIST = "AUDIO_LIST"
const AUDIO_TO_EDIT = "AUDIO_TO_EDIT"
const CLEAR_AUDIO_TO_EDIT = "CLEAR_AUDIO_TO_EDIT"
const ADD_EVENT_LIST = "ADD_EVENT_LIST"
const RESIZE = "RESIZE"
const AUDIO_FILE_TO_UPLOAD = "AUDIO_FILE_TO_UPLOAD"
const LOADED_STATE = "LOADED_STATE"
const UPLOADED_AUDIO_URL = "UPLOADED_AUDIO_URL"
const UPLOADED_AUDIO_INFORMATION = "UPLOADED_AUDIO_INFORMATION"
const CLEAR_UPLOADED_AUDIO_DATA = "CLEAR_UPLOADED_AUDIO_DATA"
const AUDIO_UPLOAD_SPEAKER = "AUDIO_UPLOAD_SPEAKER"
const AUDIO_UPLOAD_DATE = "AUDIO_UPLOAD_DATE"
const AUDIO_UPLOAD_TYPE = "AUDIO_UPLOAD_TYPE"
const AUDIO_UPLOAD_SERIES = "AUDIO_UPLOAD_SERIES"
const AUDIO_UPLOAD_REFERENCES = "AUDIO_UPLOAD_REFERENCES"
const AUDIO_DATA_READY = "AUDIO_DATA_READY"
const AUDIO_EDIT_ID = "AUDIO_EDIT_ID"
const CURRENT_EVENT = "CURRENT_EVENT"
const SIDE_PAGE_THEME = "SIDE_PAGE_THEME"
const ADMIN_SHOWCASE_TOGGLE_ON = "ADMIN_SHOWCASE_TOGGLE_ON"
const ADMIN_SHOWCASE_TOGGLE_OFF = "ADMIN_SHOWCASE_TOGGLE_OFF"


module.exports = { 
    LOGIN, 
    LOGOUT, 
    AUDIO_FILE, 
    AUDIO_PAUSE, 
    AUDIO_PLAY, 
    AUDIO_TIME, 
    AUDIO_VOLUME,
    DURATION,
    HEADER,
    CLEAR_AUDIO,
    OPEN_SIDE_PAGE,
    CLOSE_SIDE_PAGE,
    SIDE_PAGE,
    AUDIO_LIST,
    AUDIO_TO_EDIT,
    CLEAR_AUDIO_TO_EDIT,
    ADD_EVENT_LIST,
    RESIZE,
    AUDIO_FILE_TO_UPLOAD,
    UPLOADED_AUDIO_URL,
    LOADED_STATE,
    UPLOADED_AUDIO_INFORMATION,
    CLEAR_UPLOADED_AUDIO_DATA,
    AUDIO_UPLOAD_DATE,
    AUDIO_UPLOAD_REFERENCES,
    AUDIO_UPLOAD_SERIES,
    AUDIO_UPLOAD_SPEAKER,
    AUDIO_UPLOAD_TYPE,
    AUDIO_DATA_READY,
    AUDIO_EDIT_ID,
    CURRENT_EVENT,
    SIDE_PAGE_THEME,
    ADMIN_SHOWCASE_TOGGLE_ON,
    ADMIN_SHOWCASE_TOGGLE_OFF
}